apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: exam
spec:
  hard:
    requests.cpu: "2"            # Total CPU requests across all pods in the namespace
    requests.memory: "4Gi"       # Total memory requests across all pods in the namespace
    limits.cpu: "4"              # Total CPU limits across all pods in the namespace
    limits.memory: "8Gi"         # Total memory limits across all pods in the namespace
